#ifndef __WORLD_H__
#define __WORLD_H__

typedef unsigned int Model_tile_t;
#define Model_tile_default ((Model_tile_t) 0)

typedef struct
{
    Model_tile_t type;
    //Model_Agent* agent
}Model_Tile;
typedef struct
{
    int rows;
    int cols;
    Model_Tile **tiles;
}Model_Map;

/**
    @TODO find a way to have this map generated by a file
*/
void Model_Map_Init(Model_Map* this, int cols, int rows);
#endif
